defmodule AshStorageDemo.Repo.Migrations.Phase2PostAndMultiFk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:storage_attachments) do
      remove :record_id
      remove :record_type

      add :user_id,
          references(:users,
            column: :id,
            name: "storage_attachments_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :post_id, :uuid
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:storage_attachments) do
      modify :post_id,
             references(:posts,
               column: :id,
               name: "storage_attachments_post_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:posts) do
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "posts_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:posts, "posts_author_id_fkey")

    alter table(:posts) do
      remove :author_id
      remove :updated_at
      remove :inserted_at
      remove :body
    end

    drop constraint(:storage_attachments, "storage_attachments_post_id_fkey")

    alter table(:storage_attachments) do
      modify :post_id, :uuid
    end

    drop table(:posts)

    drop constraint(:storage_attachments, "storage_attachments_user_id_fkey")

    alter table(:storage_attachments) do
      remove :post_id
      remove :user_id
      add :record_type, :text, null: false
      add :record_id, :text, null: false
    end
  end
end
