defmodule AshStorageDemo.Repo.Migrations.Phase3SocialObjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "stories_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:storage_sticker_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :blob_id,
          references(:storage_blobs,
            column: :id,
            name: "storage_sticker_attachments_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :reaction_id, :uuid
    end

    alter table(:storage_attachments) do
      add :comment_id, :uuid
      add :story_id, :uuid
      add :message_id, :uuid
    end

    create table(:reactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:storage_sticker_attachments) do
      modify :reaction_id,
             references(:reactions,
               column: :id,
               name: "storage_sticker_attachments_reaction_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:reactions) do
      add :emoji, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :post_id,
          references(:posts,
            column: :id,
            name: "reactions_post_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "reactions_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sender_id,
          references(:users,
            column: :id,
            name: "messages_sender_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :recipient_id,
          references(:users,
            column: :id,
            name: "messages_recipient_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:storage_attachments) do
      modify :comment_id,
             references(:comments,
               column: :id,
               name: "storage_attachments_comment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :story_id,
             references(:stories,
               column: :id,
               name: "storage_attachments_story_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :message_id,
             references(:messages,
               column: :id,
               name: "storage_attachments_message_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:comments) do
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :post_id,
          references(:posts,
            column: :id,
            name: "comments_post_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "comments_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:comments, "comments_post_id_fkey")

    drop constraint(:comments, "comments_author_id_fkey")

    alter table(:comments) do
      remove :author_id
      remove :post_id
      remove :updated_at
      remove :inserted_at
      remove :body
    end

    drop constraint(:storage_attachments, "storage_attachments_comment_id_fkey")

    drop constraint(:storage_attachments, "storage_attachments_story_id_fkey")

    drop constraint(:storage_attachments, "storage_attachments_message_id_fkey")

    alter table(:storage_attachments) do
      modify :message_id, :uuid
      modify :story_id, :uuid
      modify :comment_id, :uuid
    end

    drop table(:comments)

    drop constraint(:messages, "messages_sender_id_fkey")

    drop constraint(:messages, "messages_recipient_id_fkey")

    drop table(:messages)

    drop constraint(:reactions, "reactions_post_id_fkey")

    drop constraint(:reactions, "reactions_author_id_fkey")

    alter table(:reactions) do
      remove :author_id
      remove :post_id
      remove :updated_at
      remove :inserted_at
      remove :emoji
    end

    drop constraint(:storage_sticker_attachments, "storage_sticker_attachments_reaction_id_fkey")

    alter table(:storage_sticker_attachments) do
      modify :reaction_id, :uuid
    end

    drop table(:reactions)

    alter table(:storage_attachments) do
      remove :message_id
      remove :story_id
      remove :comment_id
    end

    drop constraint(:storage_sticker_attachments, "storage_sticker_attachments_blob_id_fkey")

    drop table(:storage_sticker_attachments)

    drop constraint(:stories, "stories_author_id_fkey")

    drop table(:stories)
  end
end
