defmodule AshStorageDemo.Repo.Migrations.AddPasswordStrategy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :hashed_password, :text, null: false
    end

    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :taggable_type, :text, null: false
      add :taggable_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tags, [:name, :taggable_type, :taggable_id],
             name: "tags_unique_per_target_index"
           )

    create table(:stories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "stories_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:storage_sticker_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :blob_id, :uuid, null: false
      add :reaction_id, :uuid
    end

    create table(:storage_poly_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :record_type, :text, null: false
      add :record_id, :text, null: false
      add :blob_id, :uuid, null: false
    end

    create table(:storage_blobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:storage_sticker_attachments) do
      modify :blob_id,
             references(:storage_blobs,
               column: :id,
               name: "storage_sticker_attachments_blob_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:storage_poly_attachments) do
      modify :blob_id,
             references(:storage_blobs,
               column: :id,
               name: "storage_poly_attachments_blob_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:storage_blobs) do
      add :key, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text
      add :byte_size, :bigint
      add :checksum, :text
      add :service_name, :text, null: false
      add :service_opts, :map, default: %{}
      add :metadata, :map, default: %{}
      add :analyzers, :map, default: %{}
      add :pending_purge, :boolean, null: false, default: false
      add :pending_analyzers, :boolean, null: false, default: false
      add :pending_variants, :boolean, null: false, default: false

      add :variant_of_blob_id,
          references(:storage_blobs,
            column: :id,
            name: "storage_blobs_variant_of_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :variant_name, :text
      add :variant_digest, :text
    end

    create table(:storage_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :blob_id,
          references(:storage_blobs,
            column: :id,
            name: "storage_attachments_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "storage_attachments_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :post_id, :uuid
      add :comment_id, :uuid
      add :story_id, :uuid
      add :message_id, :uuid
    end

    create table(:reactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:storage_sticker_attachments) do
      modify :reaction_id,
             references(:reactions,
               column: :id,
               name: "storage_sticker_attachments_reaction_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:reactions) do
      add :emoji, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :post_id, :uuid, null: false
      add :author_id, :uuid
    end

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:storage_attachments) do
      modify :post_id,
             references(:posts,
               column: :id,
               name: "storage_attachments_post_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:reactions) do
      modify :post_id,
             references(:posts,
               column: :id,
               name: "reactions_post_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "reactions_author_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:posts) do
      add :body, :text, null: false
      add :taken_at, :text
      add :camera, :text
      add :gps_lat, :float
      add :gps_lng, :float

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "posts_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sender_id,
          references(:users,
            column: :id,
            name: "messages_sender_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :recipient_id,
          references(:users,
            column: :id,
            name: "messages_recipient_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:storage_attachments) do
      modify :comment_id,
             references(:comments,
               column: :id,
               name: "storage_attachments_comment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :story_id,
             references(:stories,
               column: :id,
               name: "storage_attachments_story_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :message_id,
             references(:messages,
               column: :id,
               name: "storage_attachments_message_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:comments) do
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :post_id,
          references(:posts,
            column: :id,
            name: "comments_post_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "comments_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:comments, "comments_post_id_fkey")

    drop constraint(:comments, "comments_author_id_fkey")

    alter table(:comments) do
      remove :author_id
      remove :post_id
      remove :updated_at
      remove :inserted_at
      remove :body
    end

    drop constraint(:storage_attachments, "storage_attachments_comment_id_fkey")

    drop constraint(:storage_attachments, "storage_attachments_story_id_fkey")

    drop constraint(:storage_attachments, "storage_attachments_message_id_fkey")

    alter table(:storage_attachments) do
      modify :message_id, :uuid
      modify :story_id, :uuid
      modify :comment_id, :uuid
    end

    drop table(:comments)

    drop constraint(:messages, "messages_sender_id_fkey")

    drop constraint(:messages, "messages_recipient_id_fkey")

    drop table(:messages)

    drop constraint(:posts, "posts_author_id_fkey")

    alter table(:posts) do
      remove :author_id
      remove :updated_at
      remove :inserted_at
      remove :gps_lng
      remove :gps_lat
      remove :camera
      remove :taken_at
      remove :body
    end

    drop constraint(:reactions, "reactions_post_id_fkey")

    drop constraint(:reactions, "reactions_author_id_fkey")

    alter table(:reactions) do
      modify :author_id, :uuid
      modify :post_id, :uuid
    end

    drop constraint(:storage_attachments, "storage_attachments_post_id_fkey")

    alter table(:storage_attachments) do
      modify :post_id, :uuid
    end

    drop table(:posts)

    alter table(:reactions) do
      remove :author_id
      remove :post_id
      remove :updated_at
      remove :inserted_at
      remove :emoji
    end

    drop constraint(:storage_sticker_attachments, "storage_sticker_attachments_reaction_id_fkey")

    alter table(:storage_sticker_attachments) do
      modify :reaction_id, :uuid
    end

    drop table(:reactions)

    drop constraint(:storage_attachments, "storage_attachments_blob_id_fkey")

    drop constraint(:storage_attachments, "storage_attachments_user_id_fkey")

    drop table(:storage_attachments)

    drop constraint(:storage_blobs, "storage_blobs_variant_of_blob_id_fkey")

    alter table(:storage_blobs) do
      remove :variant_digest
      remove :variant_name
      remove :variant_of_blob_id
      remove :pending_variants
      remove :pending_analyzers
      remove :pending_purge
      remove :analyzers
      remove :metadata
      remove :service_opts
      remove :service_name
      remove :checksum
      remove :byte_size
      remove :content_type
      remove :filename
      remove :key
    end

    drop constraint(:storage_poly_attachments, "storage_poly_attachments_blob_id_fkey")

    alter table(:storage_poly_attachments) do
      modify :blob_id, :uuid
    end

    drop constraint(:storage_sticker_attachments, "storage_sticker_attachments_blob_id_fkey")

    alter table(:storage_sticker_attachments) do
      modify :blob_id, :uuid
    end

    drop table(:storage_blobs)

    drop table(:storage_poly_attachments)

    drop table(:storage_sticker_attachments)

    drop constraint(:stories, "stories_author_id_fkey")

    drop table(:stories)

    drop_if_exists unique_index(:tags, [:name, :taggable_type, :taggable_id],
                     name: "tags_unique_per_target_index"
                   )

    drop table(:tags)

    alter table(:users) do
      remove :hashed_password
    end
  end
end
