defmodule AshStorageDemo.Repo.Migrations.Phase6PolyAttachmentAndTag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :taggable_type, :text, null: false
      add :taggable_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tags, [:name, :taggable_type, :taggable_id],
             name: "tags_unique_per_target_index"
           )

    create table(:storage_poly_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :record_type, :text, null: false
      add :record_id, :text, null: false

      add :blob_id,
          references(:storage_blobs,
            column: :id,
            name: "storage_poly_attachments_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:storage_poly_attachments, "storage_poly_attachments_blob_id_fkey")

    drop table(:storage_poly_attachments)

    drop_if_exists unique_index(:tags, [:name, :taggable_type, :taggable_id],
                     name: "tags_unique_per_target_index"
                   )

    drop table(:tags)
  end
end
