defmodule AshStorageDemo.Repo.Migrations.Phase4AnalyzerAttrs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :taken_at, :text
      add :camera, :text
      add :gps_lat, :float
      add :gps_lng, :float
    end
  end

  def down do
    alter table(:posts) do
      remove :gps_lng
      remove :gps_lat
      remove :camera
      remove :taken_at
    end
  end
end
